exception BAD;

class single Main {
	pub a : real;
	pub fn curry_add(a : int) : Fn(real):int {
		fn closure(b : real) : int {
			return a + b as int;
		};
		return closure
	};
	priv fn add(p : int) {
		self.a = self.a + p;
	};
}

fn main() {
	fn add(a : int) : int {
		return a + 1;
	};
	var x = add(3);
	/*try {
		throw BAD;
	} catch {
		return;
	}*/
	var a : int = 2;
	var b = a + 1;
	print(b as str);
	throw BAD;
	return;
}
