exception EInt : int;

/*

fn main() : () {
	//try {
		var a = readln() as int;
		var b = readln() as int;
		//var c = [1,2,3,4];
		//c.len();
		//c.get(2);
		print((a * b + 1 * 2) as str);
		//throw EInt 5;
		//throw NullPtr;
	//} catch EInt a {
	//	print("error found")
	//}
}

*/

fn main() : () {
	var a = readln();
	var b = readln();
	var c = "3";
	print(add_str(add_str(a,b),c) as str)
}
