/*
exception EInt : int;

#NoExcept
fn curry(a : int) : Fn(int):int {
	fn clos(b : int) : int {
		return a + b;
	};
	return clos;
}
*/

fn main() : () {
//	try {
		var a = readln();
		var b = readln();
		print((a.len() + b.len()) as str);
		//a.add(b);
		//print(a);
//	} catch EInt a {
//		print(a as str)
//	} catch {
//		print("error exist")
//	}
}
