exception EInt : int;

#NoExcept
fn curry(a : int) : Fn(int):int {
	fn clos(b : int) : int {
		return a + b;
	};
	return clos;
}

fn divd(a : int, b : int) : int {
	if(b == 0){
		return b;
	} else {
		return a / b;
	}
}

fn main() : () {
	try {
		var a = readln();
		var b = readln();
		a.add(b);
		print(a);
	} catch EInt a {
		print(a as str)
	} catch {
		print("error exist")
	}
}
